/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e242a189-67ab-4ece-be00-c32cff69618c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_KopuvkMMc",
    "aws_user_pools_web_client_id": "pctfu7cnnp5pq2rff7keug2g8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://bqdftz6czjd3vl723qhkiiwjn4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-447m3lotgrdutl2k5glbnkwafq",
    "aws_user_files_s3_bucket": "homepage527dbfa434934421aa42369b009b64b1165234-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
